name: android_infer_plugin
version: 0.0.1
language: android
description: "Android 代码分析工具 Infer"

tags:
 - android
 - format
 - analyzer
 - facebook
 - quality
 - plugin
 - infer

public: true

# clone_in_docker: false

script_path: ./run.sh
